
export const ActionType = {
    GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_TO_CART: "REMOVE_TO_CART",
    REMOVE_ALL_CART: "REMOVE_ALL_CART",
    GET_ONE_PRODUCT: "GET_ONE_PRODUCT",
    PLACE_TO_ORDER: "PLACE_TO_ORDER",
    REFESH: "REFESH",
    GET_ALL_TYPES: "GET_ALL_TYPES",
    INITIAL_CART : "INITIAL_CART"
}

